sudo: required
dist: trusty
language: node_js

node_js:
  - 6

script:
  - npm test

deploy:
  provider: script
  script: "./deploy.sh"

cache:
  directories:
    - node_modules

branches:
  only:
    - master
