import _ from 'lodash';

export default _.mapKeys([
  'APP_GET_API_KEYS',
  'APP_GET_LOGIN',
  'APP_GET_SIGNUP',
  'SKILLS_GET_METRICS_SKILLS',
  'SKILLS_GET_LANGUAGE_OPTIONS',
  'SKILLS_GET_GROUP_OPTIONS',
  'SKILLS_GET_SKILL_LIST',
  'SKILLS_SET_FILTER_TYPE',
  'SKILLS_SET_LANGUAGE_FILTER',
  'SKILLS_SET_ORDER_BY_FILTER',
  'SKILLS_SET_CATEGORY_FILTER',
  'SKILLS_SET_SEARCH_FILTER',
  'SKILLS_SET_STAFFPICK_FILTER',
  'SKILLS_SET_REVIEW_FILTER',
  'SKILLS_SET_STAR_RATING_FILTER',
  'SKILLS_SET_TIME_FILTER',
  'SKILLS_SET_VIEWTYPE',
  'SKILLS_SET_SKILLS_PER_PAGE',
  'SKILLS_SET_PAGE_NUMBER',
  'SKILLS_SET_SKILLS_LOADING',
]);
